### ISSUE TITLE
replicaCount variable is not being used

### ISSUE THREAD

**Issue by arovira** [bastionzero/charts#11]
[Replica count variable](https://github.com/bastionzero/charts/blob/main/charts/bctlquickstart/values.yaml#L5) is not being used on [agent deployment](https://github.com/bastionzero/charts/blob/main/charts/bctlquickstart/templates/agent/bctl-agent-deployment.yaml#L13)

**Comment by lipmas** [comment]
Hi @arovira thanks for bringing this to our attention. Unfortunately though due to some limits with our current backend architecture at this time we dont currently support multiple agent deployments running within the same cluster. We have flagged the issue and are discussing possible solutions for it. I will keep you updated if this changes in the future.

In the meantime any additional context you could provide into how you were planning to use the replica count variable or why you need to have more than 1 agent replica would be greatly appreciated.

**Comment by andreambrosio** [comment]
Hi, this would be useful when doing kubernetes clusters upgrades, or when something a node goes down, if the pod is in the node being drained, we lose connection to the cluster. Also we if for some reason the pod gets in a bad state, we are not able to login to the cluster

**Comment by calebwoofenden** [comment]
+1, this is something we really need!

**Comment by lipmas** [comment]
Hello, great news we finally addressed the backend limitation that was preventing multiple agent replicas from existing simultaneously and #27 is adding support for setting replica count in the helm chart explicitly. Additionally, we added support for utilizing [pod topology constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) to create highly available agent deployments if that is something you are interested in using.

Both of these chart values will be available in upcoming version `2.3.0`.
